[platformio]
default_envs = reterminal_e1005

[env:reterminal_e1005]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git#9ba53b691fb007d9c1b8fd37600cc71d6702125a
board = seeed-xiao-esp32-s3-sense
framework = arduino
upload_speed = 115200
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_build.flash_size = 32MB
board_build.partitions = ../common/reterminal_ota.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 3145728
lib_ldf_mode = deep+
build_flags =
    -D BOARD_HAS_PSRAM
    -D MINIZ_ENABLE_ARCHIVE_APIS
    -D RETERMINAL_MODEL=1005
    -I src
    -I ../common/include
    -I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
    -I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WebServer/src
    -I ../common-config-portal/include
lib_deps =
    symlink://../common
    symlink://../common-config-portal
    symlink://../image_pipeline
    https://github.com/Seeed-Studio/Seeed_GFX.git#a2de1abca0597c202193f22d01e9fa35d1ff613b
    adafruit/Adafruit SHT4x Library @ ^1.0.5
    bblanchon/ArduinoJson @ ^7.4.2
    ricmoo/QRCode @ ^0.0.1
